[package]
name = 'mitata'
license = 'MIT'
edition = '2021'
version = '0.0.7'
description = 'benchmarking lib/cli'

[dependencies]
clap = { version = '3', default-features = false, features = ['std', 'env', 'cargo', 'color'] }